### ISSUE TITLE
Validating SHA-OUT signatures

### ISSUE THREAD

**Issue by shannonschaerer** [OFFLINE-GmbH/postfinance#1]
Firstly, thanks for the great package. It has simplified my work drastically. I am currently trying to validate SHA-OUT signatures using your instructions but am not able to validate. Is there any way that the TEST feedback from PostFinance is causing it to not validate, or do I need to keep looking?

**Comment by tobias-kuendig** [comment]
There can be many reasons your signature won't validate. I suggest you have a look at the generated [`$hashString`](https://github.com/OFFLINE-GmbH/postfinance/blob/master/src/Offline/PaymentGateways/PostFinance.php#L120) variable and make sure that it does not contain any invalid data. Also make sure that the spec did not change since this library is already 2 years old.

Try to generate your hashstring and hash manually and then compare that to the one generated by the library.
